name: Build Qt5 Static Libraries

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  QT_VERSION: 5.15.2
  VSVER: 2019
  VCPKG_ROOT: C:\vcpkg
  VCPKG_DEFAULT_TRIPLET: x64-windows-static

jobs:
  build:
    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup vcpkg
      shell: cmd
      run: |
        git clone https://github.com/Microsoft/vcpkg.git %VCPKG_ROOT%
        cd %VCPKG_ROOT%
        .\bootstrap-vcpkg.bat
        .\vcpkg.exe integrate install
    
    - name: Cache vcpkg
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.VCPKG_ROOT }}\installed
          ${{ env.VCPKG_ROOT }}\packages
        key: vcpkg-${{ runner.os }}-${{ env.VCPKG_DEFAULT_TRIPLET }}-qt5
    
    - name: Install Qt5 Components
      shell: cmd
      run: |
        %VCPKG_ROOT%\vcpkg.exe install ^
        qt5-base:x64-windows-static ^
        qt5-multimedia:x64-windows-static ^
        qt5-tools:x64-windows-static ^
        qt5-declarative:x64-windows-static ^
        qt5-activeqt:x64-windows-static ^
        qt5-imageformats:x64-windows-static ^
        qt5-svg:x64-windows-static ^
        qt5-charts:x64-windows-static ^
        qt5-networkauth:x64-windows-static ^
        qt5-winextras:x64-windows-static
        
    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Setup Visual Studio Environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        vsversion: ${{ env.VSVER }}
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: qt5-static-msvc${{ env.VSVER }}
        path: ${{ env.VCPKG_ROOT }}/installed/x64-windows-static
        retention-days: 90 